<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.2 (doctrine2-annotation) on 2016-04-18 13:28:07.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Entity\Country
 *
 * @ORM\Entity(repositoryClass="CountryRepository")
 * @ORM\Table(name="Country")
 */
class Country
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=3)
     */
    protected $countrycode;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $percentage;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $code;

    /**
     * @ORM\OneToMany(targetEntity="VatType", mappedBy="country")
     * @ORM\JoinColumn(name="countrycode", referencedColumnName="country", nullable=false)
     */
    protected $vatTypes;

    public function __construct()
    {
        $this->vatTypes = new ArrayCollection();
    }

    /**
     * Set the value of countrycode.
     *
     * @param string $countrycode
     * @return \Entity\Country
     */
    public function setCountrycode($countrycode)
    {
        $this->countrycode = $countrycode;

        return $this;
    }

    /**
     * Get the value of countrycode.
     *
     * @return string
     */
    public function getCountrycode()
    {
        return $this->countrycode;
    }

    /**
     * Set the value of percentage.
     *
     * @param string $percentage
     * @return \Entity\Country
     */
    public function setPercentage($percentage)
    {
        $this->percentage = $percentage;

        return $this;
    }

    /**
     * Get the value of percentage.
     *
     * @return string
     */
    public function getPercentage()
    {
        return $this->percentage;
    }

    /**
     * Set the value of code.
     *
     * @param string $code
     * @return \Entity\Country
     */
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get the value of code.
     *
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Add VatType entity to collection (one to many).
     *
     * @param \Entity\VatType $vatType
     * @return \Entity\Country
     */
    public function addVatType(VatType $vatType)
    {
        $this->vatTypes[] = $vatType;

        return $this;
    }

    /**
     * Remove VatType entity from collection (one to many).
     *
     * @param \Entity\VatType $vatType
     * @return \Entity\Country
     */
    public function removeVatType(VatType $vatType)
    {
        $this->vatTypes->removeElement($vatType);

        return $this;
    }

    /**
     * Get VatType entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getVatTypes()
    {
        return $this->vatTypes;
    }

    public function __sleep()
    {
        return array('countrycode', 'percentage', 'code');
    }
}