<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.2 (doctrine2-annotation) on 2016-04-29 10:04:43.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Integrated\Bundle\SubscriptionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Integrated\Bundle\SubscriptionBundle\Entity\SubscriptionTypeVariant
 *
 * @ORM\Entity()
 * @ORM\Table(name="subscription_type_variant")
 */
class SubscriptionTypeVariant
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=36, nullable=true)
     */
    protected $subscription_type_id;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2)
     */
    protected $price;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=3, nullable=true)
     */
    protected $vat;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2, nullable=true)
     */
    protected $pricevat;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $periodtype;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $periodlentgh;

    /**
     * @ORM\ManyToOne(targetEntity="SubscriptionType", inversedBy="subscriptionTypeVariants")
     * @ORM\JoinColumn(name="subscription_type_id", referencedColumnName="id")
     */
    protected $subscriptionType;

    public function __construct()
    {
    }

    /**
     * Set the value of subscription_type_id.
     *
     * @param string $subscription_type_id
     * @return \Integrated\Bundle\SubscriptionBundle\Entity\SubscriptionTypeVariant
     */
    public function setSubscriptionTypeId($subscription_type_id)
    {
        $this->subscription_type_id = $subscription_type_id;

        return $this;
    }

    /**
     * Get the value of subscription_type_id.
     *
     * @return string
     */
    public function getSubscriptionTypeId()
    {
        return $this->subscription_type_id;
    }

    /**
     * Set the value of price.
     *
     * @param float $price
     * @return \Integrated\Bundle\SubscriptionBundle\Entity\SubscriptionTypeVariant
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Get the value of price.
     *
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Set the value of vat.
     *
     * @param float $vat
     * @return \Integrated\Bundle\SubscriptionBundle\Entity\SubscriptionTypeVariant
     */
    public function setVat($vat)
    {
        $this->vat = $vat;

        return $this;
    }

    /**
     * Get the value of vat.
     *
     * @return float
     */
    public function getVat()
    {
        return $this->vat;
    }

    /**
     * Set the value of pricevat.
     *
     * @param float $pricevat
     * @return \Integrated\Bundle\SubscriptionBundle\Entity\SubscriptionTypeVariant
     */
    public function setPricevat($pricevat)
    {
        $this->pricevat = $pricevat;

        return $this;
    }

    /**
     * Get the value of pricevat.
     *
     * @return float
     */
    public function getPricevat()
    {
        return $this->pricevat;
    }

    /**
     * Set the value of periodtype.
     *
     * @param string $periodtype
     * @return \Integrated\Bundle\SubscriptionBundle\Entity\SubscriptionTypeVariant
     */
    public function setPeriodtype($periodtype)
    {
        $this->periodtype = $periodtype;

        return $this;
    }

    /**
     * Get the value of periodtype.
     *
     * @return string
     */
    public function getPeriodtype()
    {
        return $this->periodtype;
    }

    /**
     * Set the value of periodlentgh.
     *
     * @param integer $periodlentgh
     * @return \Integrated\Bundle\SubscriptionBundle\Entity\SubscriptionTypeVariant
     */
    public function setPeriodlentgh($periodlentgh)
    {
        $this->periodlentgh = $periodlentgh;

        return $this;
    }

    /**
     * Get the value of periodlentgh.
     *
     * @return integer
     */
    public function getPeriodlentgh()
    {
        return $this->periodlentgh;
    }

    /**
     * Set SubscriptionType entity (many to one).
     *
     * @param \Integrated\Bundle\SubscriptionBundle\Entity\SubscriptionType $subscriptionType
     * @return \Integrated\Bundle\SubscriptionBundle\Entity\SubscriptionTypeVariant
     */
    public function setSubscriptionType(SubscriptionType $subscriptionType = null)
    {
        $this->subscriptionType = $subscriptionType;

        return $this;
    }

    /**
     * Get SubscriptionType entity (many to one).
     *
     * @return \Integrated\Bundle\SubscriptionBundle\Entity\SubscriptionType
     */
    public function getSubscriptionType()
    {
        return $this->subscriptionType;
    }

    public function __sleep()
    {
        return array('subscription_type_id', 'price', 'vat', 'pricevat', 'periodtype', 'periodlentgh');
    }
}