<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.2 (doctrine2-annotation) on 2016-04-18 13:28:07.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Integrated\Bundle\SubscriptionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity\Subscription
 *
 * @ORM\Entity(repositoryClass="SubscriptionRepository")
 * @ORM\Table(name="subscription", indexes={@ORM\Index(name="fk_Subscription_SubscriptionType1_idx", columns={"`type`"})})
 */
class Subscription
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=45)
     */
    protected $id;

    /**
     * @ORM\Column(name="`type`", type="string", length=45)
     */
    protected $type;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $relation;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $contact;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2, nullable=true)
     */
    protected $customprice;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2, nullable=true)
     */
    protected $discountprice;

    /**
     * @ORM\Column(type="decimal", precision=2, scale=3, nullable=true)
     */
    protected $discountpercentage;

    /**
     * @ORM\Column(name="`status`", type="string", nullable=true)
     */
    protected $status;

    /**
     * @ORM\ManyToOne(targetEntity="SubscriptionType", inversedBy="subscriptions")
     * @ORM\JoinColumn(name="`type`", referencedColumnName="id", nullable=false)
     */
    protected $subscriptionType;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param string $id
     * @return \Entity\Subscription
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of type.
     *
     * @param string $type
     * @return \Entity\Subscription
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get the value of type.
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set the value of relation.
     *
     * @param string $relation
     * @return \Entity\Subscription
     */
    public function setRelation($relation)
    {
        $this->relation = $relation;

        return $this;
    }

    /**
     * Get the value of relation.
     *
     * @return string
     */
    public function getRelation()
    {
        return $this->relation;
    }

    /**
     * Set the value of contact.
     *
     * @param string $contact
     * @return \Entity\Subscription
     */
    public function setContact($contact)
    {
        $this->contact = $contact;

        return $this;
    }

    /**
     * Get the value of contact.
     *
     * @return string
     */
    public function getContact()
    {
        return $this->contact;
    }

    /**
     * Set the value of customprice.
     *
     * @param float $customprice
     * @return \Entity\Subscription
     */
    public function setCustomprice($customprice)
    {
        $this->customprice = $customprice;

        return $this;
    }

    /**
     * Get the value of customprice.
     *
     * @return float
     */
    public function getCustomprice()
    {
        return $this->customprice;
    }

    /**
     * Set the value of discountprice.
     *
     * @param float $discountprice
     * @return \Entity\Subscription
     */
    public function setDiscountprice($discountprice)
    {
        $this->discountprice = $discountprice;

        return $this;
    }

    /**
     * Get the value of discountprice.
     *
     * @return float
     */
    public function getDiscountprice()
    {
        return $this->discountprice;
    }

    /**
     * Set the value of discountpercentage.
     *
     * @param float $discountpercentage
     * @return \Entity\Subscription
     */
    public function setDiscountpercentage($discountpercentage)
    {
        $this->discountpercentage = $discountpercentage;

        return $this;
    }

    /**
     * Get the value of discountpercentage.
     *
     * @return float
     */
    public function getDiscountpercentage()
    {
        return $this->discountpercentage;
    }

    /**
     * Set the value of status.
     *
     * @param string $status
     * @return \Entity\Subscription
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get the value of status.
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set SubscriptionType entity (many to one).
     *
     * @param \Entity\SubscriptionType $subscriptionType
     * @return \Entity\Subscription
     */
    public function setSubscriptionType(SubscriptionType $subscriptionType = null)
    {
        $this->subscriptionType = $subscriptionType;

        return $this;
    }

    /**
     * Get SubscriptionType entity (many to one).
     *
     * @return \Entity\SubscriptionType
     */
    public function getSubscriptionType()
    {
        return $this->subscriptionType;
    }

    public function __sleep()
    {
        return array('id', 'type', 'relation', 'contact', 'customprice', 'discountprice', 'discountpercentage', 'status');
    }
}