<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.2 (doctrine2-annotation) on 2016-04-29 10:04:43.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Integrated\Bundle\SubscriptionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Integrated\Bundle\SubscriptionBundle\Entity\SubscriptionType
 */
class SubscriptionType
{
    protected $id;

    protected $name;

    protected $teaser;

    protected $startDate;

    protected $endDate;

    protected $condition;

    protected $disabled;

    protected $channels;

    protected $typeVat;

    protected $subscriptions;

    protected $subscriptionTypeVariants;

    protected $vatType;

    protected $subscriptionWalls;

    public function __construct()
    {
        $this->subscriptions = new ArrayCollection();
        $this->subscriptionTypeVariants = new ArrayCollection();
        $this->subscriptionWalls = new ArrayCollection();
    }

    /**
     * @param string $id
     * @return SubscriptionType
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $name
     * @return SubscriptionType
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $teaser
     * @return SubscriptionType
     */
    public function setTeaser($teaser)
    {
        $this->teaser = $teaser;

        return $this;
    }

    /**
     * @return string
     */
    public function getTeaser()
    {
        return $this->teaser;
    }

    /**
     * @param \DateTime $startDate
     * @return SubscriptionType
     */
    public function setStartDate($startDate)
    {
        $this->startDate = $startDate;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * @param \DateTime $endDate
     * @return SubscriptionType
     */
    public function setEndDate($endDate)
    {
        $this->endDate = $endDate;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * @param string $condition
     * @return SubscriptionType
     */
    public function setCondition($condition)
    {
        $this->condition = $condition;

        return $this;
    }

    /**
     * @return string
     */
    public function getCondition()
    {
        return $this->condition;
    }

    /**
     * @param boolean $disabled
     * @return SubscriptionType
     */
    public function setDisabled($disabled)
    {
        $this->disabled = $disabled;

        return $this;
    }

    /**
     * @return boolean
     */
    public function getDisabled()
    {
        return $this->disabled;
    }

    /**
     * @param string $channels
     * @return SubscriptionType
     */
    public function setChannels($channels)
    {
        $this->channels = $channels;

        return $this;
    }

    /**
     * @return string
     */
    public function getChannels()
    {
        return $this->channels;
    }

    /**
     * @param string $typevat
     * @return SubscriptionType
     */
    public function setTypevat($typevat)
    {
        $this->typevat = $typevat;

        return $this;
    }

    /**
     * @return string
     */
    public function getTypevat()
    {
        return $this->typevat;
    }

    /**
     * Add Subscription entity to collection (one to many).
     *
     * @param Subscription $subscription
     * @return SubscriptionType
     */
    public function addSubscription(Subscription $subscription)
    {
        $this->subscriptions->add($subscription);

        return $this;
    }

    /**
     * Remove Subscription entity from collection (one to many).
     *
     * @param Subscription $subscription
     * @return SubscriptionType
     */
    public function removeSubscription(Subscription $subscription)
    {
        $this->subscriptions->removeElement($subscription);

        return $this;
    }

    /**
     * Get Subscription entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSubscriptions()
    {
        return $this->subscriptions;
    }

    /**
     * Add SubscriptionTypeVariant entity to collection (one to many).
     *
     * @param SubscriptionTypeVariant $subscriptionTypeVariant
     * @return SubscriptionType
     */
    public function addSubscriptionTypeVariant(SubscriptionTypeVariant $subscriptionTypeVariant)
    {
        $this->subscriptionTypeVariants->add($subscriptionTypeVariant);

        return $this;
    }

    /**
     * Remove SubscriptionTypeVariant entity from collection (one to many).
     *
     * @param SubscriptionTypeVariant $subscriptionTypeVariant
     * @return SubscriptionType
     */
    public function removeSubscriptionTypeVariant(SubscriptionTypeVariant $subscriptionTypeVariant)
    {
        $this->subscriptionTypeVariants->removeElement($subscriptionTypeVariant);

        return $this;
    }

    /**
     * Get SubscriptionTypeVariant entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSubscriptionTypeVariants()
    {
        return $this->subscriptionTypeVariants;
    }

    /**
     * Set VatType entity (many to one).
     *
     * @param VatType $vatType
     * @return SubscriptionType
     */
    public function setVatType(VatType $vatType = null)
    {
        $this->vatType = $vatType;

        return $this;
    }

    /**
     * Get VatType entity (many to one).
     *
     * @return VatType
     */
    public function getVatType()
    {
        return $this->vatType;
    }

    /**
     * Add SubscriptionWall entity to collection.
     *
     * @param SubscriptionWall $subscriptionWall
     * @return SubscriptionType
     */
    public function addSubscriptionWall(SubscriptionWall $subscriptionWall)
    {
        $subscriptionWall->addSubscriptionType($this);
        $this->subscriptionWalls->add($subscriptionWall);

        return $this;
    }

    /**
     * Remove SubscriptionWall entity from collection.
     *
     * @param SubscriptionWall $subscriptionWall
     * @return SubscriptionType
     */
    public function removeSubscriptionWall(SubscriptionWall $subscriptionWall)
    {
        $subscriptionWall->removeSubscriptionType($this);
        $this->subscriptionWalls->removeElement($subscriptionWall);

        return $this;
    }

    /**
     * Get SubscriptionWall entity collection.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSubscriptionWalls()
    {
        return $this->subscriptionWalls;
    }
}