<?php

/**
 * Auto generated by Jacob Workbench Schema Exporter.
 * Version 3.0.2 (doctrine2-annotation) on 2016-04-18 13:28:07.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Integrated\Bundle\SubscriptionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity\SubscriptionWall
 *
 * @ORM\Entity(repositoryClass="SubscriptionWallRepository")
 * @ORM\Table(name="subscription_wall", indexes={@ORM\Index(name="fk_SubscriptionWall_SubscriptionType1_idx", columns={"`type`"})})
 */
class SubscriptionWall
{
    /**
     * @ORM\Column(type="guid")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     */
    protected $id;

    /**
     * @ORM\Column(name="`name`", type="string", length=200, nullable=true)
     */
    protected $name;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    protected $teaser;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $disabled;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $freetier;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $channels;

    /**
     * @ORM\Column(name="`type`", type="string", length=45, nullable=true)
     */
    protected $type;

    /**
     * @ORM\Column(name="`values`", type="string", length=45, nullable=true)
     */
    protected $values;

    /**
     * @ORM\ManyToOne(targetEntity="SubscriptionType", inversedBy="subscriptionWalls")
     * @ORM\JoinColumn(name="`type`", referencedColumnName="id", nullable=false)
     */
    protected $subscriptionType;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param string $id
     * @return \Entity\SubscriptionWall
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of name.
     *
     * @param string $name
     * @return \Entity\SubscriptionWall
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get the value of name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set the value of teaser.
     *
     * @param string $teaser
     * @return \Entity\SubscriptionWall
     */
    public function setTeaser($teaser)
    {
        $this->teaser = $teaser;

        return $this;
    }

    /**
     * Get the value of teaser.
     *
     * @return string
     */
    public function getTeaser()
    {
        return $this->teaser;
    }

    /**
     * Set the value of disabled.
     *
     * @param boolean $disabled
     * @return \Entity\SubscriptionWall
     */
    public function setDisabled($disabled)
    {
        $this->disabled = $disabled;

        return $this;
    }

    /**
     * Get the value of disabled.
     *
     * @return boolean
     */
    public function getDisabled()
    {
        return $this->disabled;
    }

    /**
     * Set the value of freetier.
     *
     * @param string $freetier
     * @return \Entity\SubscriptionWall
     */
    public function setFreetier($freetier)
    {
        $this->freetier = $freetier;

        return $this;
    }

    /**
     * Get the value of freetier.
     *
     * @return string
     */
    public function getFreetier()
    {
        return $this->freetier;
    }

    /**
     * Set the value of channels.
     *
     * @param string $channels
     * @return \Entity\SubscriptionWall
     */
    public function setChannels($channels)
    {
        $this->channels = $channels;

        return $this;
    }

    /**
     * Get the value of channels.
     *
     * @return string
     */
    public function getChannels()
    {
        return $this->channels;
    }

    /**
     * Set the value of type.
     *
     * @param integer $type
     * @return \Entity\SubscriptionWall
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get the value of type.
     *
     * @return integer
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set the value of values.
     *
     * @param string $values
     * @return \Entity\SubscriptionWall
     */
    public function setValues($values)
    {
        $this->values = $values;

        return $this;
    }

    /**
     * Get the value of values.
     *
     * @return string
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Set SubscriptionType entity (many to one).
     *
     * @param \Entity\SubscriptionType $subscriptionType
     * @return \Entity\SubscriptionWall
     */
    public function setSubscriptionType(SubscriptionType $subscriptionType = null)
    {
        $this->subscriptionType = $subscriptionType;

        return $this;
    }

    /**
     * Get SubscriptionType entity (many to one).
     *
     * @return \Entity\SubscriptionType
     */
    public function getSubscriptionType()
    {
        return $this->subscriptionType;
    }

    public function __sleep()
    {
        return array('id', 'name', 'teaser', 'disabled', 'freetier', 'channels', 'type', 'values');
    }

}