<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.2 (doctrine2-annotation) on 2016-04-22 11:53:36.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Integrated\Bundle\SubscriptionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Entity\VatContinent
 *
 * @ORM\Entity(repositoryClass="VatContinentRepository")
 * @ORM\Table(name="vat_continent")
 */
class VatContinent
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=2)
     */
    protected $continentcode;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=3)
     */
    protected $percentage;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $code;

    /**
     * @ORM\OneToMany(targetEntity="VatType", mappedBy="vatContinent")
     * @ORM\JoinColumn(name="continentcode", referencedColumnName="continent", nullable=false)
     */
    protected $vatTypes;

    public function __construct()
    {
        $this->vatTypes = new ArrayCollection();
    }

    /**
     * Set the value of continentcode.
     *
     * @param string $continentcode
     * @return \Entity\VatContinent
     */
    public function setContinentcode($continentcode)
    {
        $this->continentcode = $continentcode;

        return $this;
    }

    /**
     * Get the value of continentcode.
     *
     * @return string
     */
    public function getContinentcode()
    {
        return $this->continentcode;
    }

    /**
     * Set the value of percentage.
     *
     * @param float $percentage
     * @return \Entity\VatContinent
     */
    public function setPercentage($percentage)
    {
        $this->percentage = $percentage;

        return $this;
    }

    /**
     * Get the value of percentage.
     *
     * @return float
     */
    public function getPercentage()
    {
        return $this->percentage;
    }

    /**
     * Set the value of code.
     *
     * @param string $code
     * @return \Entity\VatContinent
     */
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get the value of code.
     *
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Add VatType entity to collection (one to many).
     *
     * @param \Entity\VatType $vatType
     * @return \Entity\VatContinent
     */
    public function addVatType(VatType $vatType)
    {
        $this->vatTypes[] = $vatType;

        return $this;
    }

    /**
     * Remove VatType entity from collection (one to many).
     *
     * @param \Entity\VatType $vatType
     * @return \Entity\VatContinent
     */
    public function removeVatType(VatType $vatType)
    {
        $this->vatTypes->removeElement($vatType);

        return $this;
    }

    /**
     * Get VatType entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getVatTypes()
    {
        return $this->vatTypes;
    }

    public function __sleep()
    {
        return array('continentcode', 'percentage', 'code');
    }
}