<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.2 (doctrine2-annotation) on 2016-04-26 12:32:33.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Integrated\Bundle\SubscriptionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Integrated\Bundle\SubscriptionBundle\Entity\VatCountry
 *
 * @ORM\Entity()
 * @ORM\Table(name="vat_country")
 */
class VatCountry
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=3)
     */
    protected $countrycode;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=3)
     */
    protected $percentage;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $code;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $disablewithvatid;

    /**
     * @ORM\OneToMany(targetEntity="VatType", mappedBy="vatCountry")
     * @ORM\JoinColumn(name="countrycode", referencedColumnName="country", nullable=false)
     */
    protected $vatTypes;

    public function __construct()
    {
        $this->vatTypes = new ArrayCollection();
    }

    /**
     * Set the value of countrycode.
     *
     * @param string $countrycode
     * @return \Integrated\Bundle\SubscriptionBundle\Entity\VatCountry
     */
    public function setCountrycode($countrycode)
    {
        $this->countrycode = $countrycode;

        return $this;
    }

    /**
     * Get the value of countrycode.
     *
     * @return string
     */
    public function getCountrycode()
    {
        return $this->countrycode;
    }

    /**
     * Set the value of percentage.
     *
     * @param float $percentage
     * @return \Integrated\Bundle\SubscriptionBundle\Entity\VatCountry
     */
    public function setPercentage($percentage)
    {
        $this->percentage = $percentage;

        return $this;
    }

    /**
     * Get the value of percentage.
     *
     * @return float
     */
    public function getPercentage()
    {
        return $this->percentage;
    }

    /**
     * Set the value of code.
     *
     * @param string $code
     * @return \Integrated\Bundle\SubscriptionBundle\Entity\VatCountry
     */
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get the value of code.
     *
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Set the value of disablewithvatid.
     *
     * @param boolean $disablewithvatid
     * @return \Integrated\Bundle\SubscriptionBundle\Entity\VatCountry
     */
    public function setDisablewithvatid($disablewithvatid)
    {
        $this->disablewithvatid = $disablewithvatid;

        return $this;
    }

    /**
     * Get the value of disablewithvatid.
     *
     * @return boolean
     */
    public function getDisablewithvatid()
    {
        return $this->disablewithvatid;
    }

    /**
     * Add VatType entity to collection (one to many).
     *
     * @param \Integrated\Bundle\SubscriptionBundle\Entity\VatType $vatType
     * @return \Integrated\Bundle\SubscriptionBundle\Entity\VatCountry
     */
    public function addVatType(VatType $vatType)
    {
        $this->vatTypes[] = $vatType;

        return $this;
    }

    /**
     * Remove VatType entity from collection (one to many).
     *
     * @param \Integrated\Bundle\SubscriptionBundle\Entity\VatType $vatType
     * @return \Integrated\Bundle\SubscriptionBundle\Entity\VatCountry
     */
    public function removeVatType(VatType $vatType)
    {
        $this->vatTypes->removeElement($vatType);

        return $this;
    }

    /**
     * Get VatType entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getVatTypes()
    {
        return $this->vatTypes;
    }

    public function __sleep()
    {
        return array('countrycode', 'percentage', 'code', 'disablewithvatid');
    }
}