<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.2 (doctrine2-annotation) on 2016-04-22 10:51:55.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Entity\VatType
 *
 * @ORM\Entity(repositoryClass="VatTypeRepository")
 * @ORM\Table(name="vat_type", indexes={@ORM\Index(name="fk_vat_type_vat_country1_idx", columns={"country"}), @ORM\Index(name="fk_vat_type_vat_continent1_idx", columns={"continent"})})
 */
class VatType
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=255)
     */
    protected $id;

    /**
     * @ORM\Column(name="`name`", type="string", length=45)
     */
    protected $name;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=3, nullable=true)
     */
    protected $percentage;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $code;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $dissablebyvatin;

    /**
     * @ORM\Column(type="string", length=3, nullable=true)
     */
    protected $country;

    /**
     * @ORM\Column(type="string", length=2, nullable=true)
     */
    protected $continent;

    /**
     * @ORM\OneToMany(targetEntity="SubscriptionType", mappedBy="vatType")
     * @ORM\JoinColumn(name="id", referencedColumnName="vattype", nullable=false)
     */
    protected $subscriptionTypes;

    /**
     * @ORM\ManyToOne(targetEntity="VatCountry", inversedBy="vatTypes")
     * @ORM\JoinColumn(name="country", referencedColumnName="countrycode")
     */
    protected $vatCountry;

    /**
     * @ORM\ManyToOne(targetEntity="VatContinent", inversedBy="vatTypes")
     * @ORM\JoinColumn(name="continent", referencedColumnName="continentcode")
     */
    protected $vatContinent;

    public function __construct()
    {
        $this->subscriptionTypes = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param string $id
     * @return \Entity\VatType
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of name.
     *
     * @param string $name
     * @return \Entity\VatType
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get the value of name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set the value of percentage.
     *
     * @param float $percentage
     * @return \Entity\VatType
     */
    public function setPercentage($percentage)
    {
        $this->percentage = $percentage;

        return $this;
    }

    /**
     * Get the value of percentage.
     *
     * @return float
     */
    public function getPercentage()
    {
        return $this->percentage;
    }

    /**
     * Set the value of code.
     *
     * @param string $code
     * @return \Entity\VatType
     */
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get the value of code.
     *
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Set the value of dissablebyvatin.
     *
     * @param boolean $dissablebyvatin
     * @return \Entity\VatType
     */
    public function setDissablebyvatin($dissablebyvatin)
    {
        $this->dissablebyvatin = $dissablebyvatin;

        return $this;
    }

    /**
     * Get the value of dissablebyvatin.
     *
     * @return boolean
     */
    public function getDissablebyvatin()
    {
        return $this->dissablebyvatin;
    }

    /**
     * Set the value of country.
     *
     * @param string $country
     * @return \Entity\VatType
     */
    public function setCountry($country)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Get the value of country.
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Set the value of continent.
     *
     * @param string $continent
     * @return \Entity\VatType
     */
    public function setContinent($continent)
    {
        $this->continent = $continent;

        return $this;
    }

    /**
     * Get the value of continent.
     *
     * @return string
     */
    public function getContinent()
    {
        return $this->continent;
    }

    /**
     * Add SubscriptionType entity to collection (one to many).
     *
     * @param \Entity\SubscriptionType $subscriptionType
     * @return \Entity\VatType
     */
    public function addSubscriptionType(SubscriptionType $subscriptionType)
    {
        $this->subscriptionTypes[] = $subscriptionType;

        return $this;
    }

    /**
     * Remove SubscriptionType entity from collection (one to many).
     *
     * @param \Entity\SubscriptionType $subscriptionType
     * @return \Entity\VatType
     */
    public function removeSubscriptionType(SubscriptionType $subscriptionType)
    {
        $this->subscriptionTypes->removeElement($subscriptionType);

        return $this;
    }

    /**
     * Get SubscriptionType entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSubscriptionTypes()
    {
        return $this->subscriptionTypes;
    }

    /**
     * Set VatCountry entity (many to one).
     *
     * @param \Entity\VatCountry $vatCountry
     * @return \Entity\VatType
     */
    public function setVatCountry(VatCountry $vatCountry = null)
    {
        $this->vatCountry = $vatCountry;

        return $this;
    }

    /**
     * Get VatCountry entity (many to one).
     *
     * @return \Entity\VatCountry
     */
    public function getVatCountry()
    {
        return $this->vatCountry;
    }

    /**
     * Set VatContinent entity (many to one).
     *
     * @param \Entity\VatContinent $vatContinent
     * @return \Entity\VatType
     */
    public function setVatContinent(VatContinent $vatContinent = null)
    {
        $this->vatContinent = $vatContinent;

        return $this;
    }

    /**
     * Get VatContinent entity (many to one).
     *
     * @return \Entity\VatContinent
     */
    public function getVatContinent()
    {
        return $this->vatContinent;
    }

    public function __sleep()
    {
        return array('id', 'name', 'percentage', 'code', 'dissablebyvatin', 'country', 'continent');
    }
}